### ISSUE TITLE
Errors installing py122u

### ISSUE THREAD

**Issue by kooscode** [Naexys/py-acr122u#10]
I run "pip install py122u" but get following errors:

`Collecting py122u
  Using cached py122u-2.3.5-py3-none-any.whl.metadata (2.8 kB)
Collecting pyscard>=2.0.7 (from py122u)
  Using cached pyscard-2.0.7.tar.gz (152 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Using cached py122u-2.3.5-py3-none-any.whl (8.3 kB)
Building wheels for collected packages: pyscard
  Building wheel for pyscard (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyscard (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Package libpcsclite was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libpcsclite.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libpcsclite' found
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'smartcard.scard._scard' extension
      swigging smartcard/scard/scard.i to smartcard/scard/scard_wrap.c
      swig -python -outdir smartcard/scard -DPCSCLITE -o smartcard/scard/scard_wrap.c smartcard/scard/scard.i
      error: command 'swig' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyscard
Failed to build pyscard
ERROR: Could not build wheels for pyscard, which is required to install pyproject.toml-based projects`

**Comment by kooscode** [comment]
UPDATE - I got it to work by manually installing packages

APT PACKAGES:
`sudo apt install libpcsclite-dev`
`sudo apt install swig`

Python Packages:
`pip install pyscard`

This solved my problem on UBUNTU 22.04

**Comment by Flowtter** [comment]
Can you try with `pip install -I py122u` ?
